### ISSUE TITLE
How should I type a field which was removed and added back?

### ISSUE THREAD

**Issue by y-usuzumi** [lortabac/versioning#1]

**Comment by YoEight** [comment]
Save you some trouble and use a different field name. I'm not talking about a potential library limitation here but rather more about an event-sourcing standpoint (if you happen to use it in such fashion). This advice also stands if you happen to use that library in a different context. Each versioned data **must** be different from the other, otherwise, there is no point versioning them.

**Comment by lortabac** [comment]
I think it should be easy to implement a type family that takes two types and returns the first, or the second if the first is NA. I might decide to include it in the library at some point (of course contributions are welcome).
That said, YoEight's suggestion seems reasonable.

**Comment by y-usuzumi** [comment]
That does sound fair. Thank you! @YoEight  @lortabac
